[package]
name = "get_docker_image_latest_tag"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.25", features = ["json"]}
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
